export const jobPostings = [
  {
    id: '1a2b3c',
    created_at: '2024-08-01T12:00:00Z',
    company: {
      id: 'comp123',
      name: 'Tech Corp',
      description: 'A leading tech company specializing in innovative solutions.',
      logo: 'https://picsum.photos/seed/techcorp/50/50',
      cover: 'https://picsum.photos/seed/techcorp-cover/800/200',
      admin_id: 'admin123',
    },
    title: 'Front-end Developer',
    description: 'We are looking for a talented front-end developer with experience in Vue.js and Nuxt.js.',
    work_type: 'Full-time',
    status: 'Open',
    locations: 'Remote',
    industry: 'Technology',
    tags: ['JavaScript', 'Vue.js', 'Nuxt.js', 'Front-end'],
  },
  {
    id: '4d5e6f',
    created_at: '2024-07-28T09:30:00Z',
    company: {
      id: 'comp456',
      name: 'Health Solutions',
      description: 'Pioneers in healthcare technology and solutions.',
      logo: 'https://picsum.photos/seed/healthsolutions/50/50',
      cover: 'https://picsum.photos/seed/healthsolutions-cover/800/200',
      admin_id: 'admin456',
    },
    title: 'Back-end Developer',
    description: 'Join our team to build scalable and robust back-end systems.',
    work_type: 'Part-time',
    status: 'Open',
    locations: 'New York, NY',
    industry: 'Healthcare',
    tags: ['Node.js', 'Express', 'Backend'],
  },
  {
    id: '7g8h9i',
    created_at: '2024-08-03T15:45:00Z',
    company: {
      id: 'comp789',
      name: 'Finance Innovations',
      description: 'Revolutionizing financial services with cutting-edge technology.',
      logo: 'https://picsum.photos/seed/financeinnovations/50/50',
      cover: 'https://picsum.photos/seed/financeinnovations-cover/800/200',
      admin_id: 'admin789',
    },
    title: 'Data Scientist',
    description: 'Analyze and interpret complex data to help drive business decisions.',
    work_type: 'Contract',
    status: 'Open',
    locations: 'San Francisco, CA',
    industry: 'Finance',
    tags: ['Python', 'Data Analysis', 'Machine Learning'],
  },
  {
    id: '2j3k4l',
    created_at: '2024-08-05T10:20:00Z',
    company: {
      id: 'comp321',
      name: 'EduTech',
      description: 'Innovating the education sector with technology.',
      logo: 'https://picsum.photos/seed/edutech/50/50',
      cover: 'https://picsum.photos/seed/edutech-cover/800/200',
      admin_id: 'admin321',
    },
    title: 'Product Manager',
    description: 'Lead the product development team to create impactful educational tools.',
    work_type: 'Full-time',
    status: 'Open',
    locations: 'Remote',
    industry: 'Education',
    tags: ['Product Management', 'Agile', 'Leadership'],
  },
  {
    id: '5m6n7o',
    created_at: '2024-08-06T08:15:00Z',
    company: {
      id: 'comp654',
      name: 'Auto Dynamics',
      description: 'Pioneering the future of automotive technology.',
      logo: 'https://picsum.photos/seed/autodynamics/50/50',
      cover: 'https://picsum.photos/seed/autodynamics-cover/800/200',
      admin_id: 'admin654',
    },
    title: 'Mechanical Engineer',
    description: 'Design and develop advanced automotive systems.',
    work_type: 'Full-time',
    status: 'Open',
    locations: 'Detroit, MI',
    industry: 'Automotive',
    tags: ['Mechanical Engineering', 'CAD', 'Automotive'],
  },
  {
    id: '8p9q0r',
    created_at: '2024-08-07T14:40:00Z',
    company: {
      id: 'comp987',
      name: 'Green Energy',
      description: 'Leading the charge in renewable energy solutions.',
      logo: 'https://picsum.photos/seed/greenenergy/50/50',
      cover: 'https://picsum.photos/seed/greenenergy-cover/800/200',
      admin_id: 'admin987',
    },
    title: 'Project Manager',
    description: 'Manage large-scale renewable energy projects.',
    work_type: 'Full-time',
    status: 'Open',
    locations: 'Remote',
    industry: 'Energy',
    tags: ['Project Management', 'Renewable Energy', 'Leadership'],
  },
  {
    id: '1s2t3u',
    created_at: '2024-08-08T13:35:00Z',
    company: {
      id: 'comp258',
      name: 'Retail Giants',
      description: 'Transforming retail with cutting-edge digital solutions.',
      logo: 'https://picsum.photos/seed/retailgiants/50/50',
      cover: 'https://picsum.photos/seed/retailgiants-cover/800/200',
      admin_id: 'admin258',
    },
    title: 'UX Designer',
    description: 'Create intuitive and engaging user experiences for our retail platform.',
    work_type: 'Contract',
    status: 'Open',
    locations: 'Seattle, WA',
    industry: 'Retail',
    tags: ['UX Design', 'Figma', 'User Research'],
  },
  {
    id: '4v5w6x',
    created_at: '2024-08-09T11:25:00Z',
    company: {
      id: 'comp741',
      name: 'CyberDefend',
      description: 'Protecting digital infrastructure with top-tier cybersecurity solutions.',
      logo: 'https://picsum.photos/seed/cyberdefend/50/50',
      cover: 'https://picsum.photos/seed/cyberdefend-cover/800/200',
      admin_id: 'admin741',
    },
    title: 'Security Analyst',
    description: 'Monitor and analyze security threats to safeguard our clients.',
    work_type: 'Full-time',
    status: 'Open',
    locations: 'Remote',
    industry: 'Cybersecurity',
    tags: ['Cybersecurity', 'Threat Analysis', 'Network Security'],
  },
  {
    id: '7y8z9a',
    created_at: '2024-08-10T09:00:00Z',
    company: {
      id: 'comp852',
      name: 'Travel World',
      description: 'Creating unforgettable travel experiences with innovative technology.',
      logo: 'https://picsum.photos/seed/travelworld/50/50',
      cover: 'https://picsum.photos/seed/travelworld-cover/800/200',
      admin_id: 'admin852',
    },
    title: 'Marketing Specialist',
    description: 'Develop and execute marketing strategies to drive customer engagement.',
    work_type: 'Part-time',
    status: 'Open',
    locations: 'Los Angeles, CA',
    industry: 'Travel',
    tags: ['Marketing', 'SEO', 'Content Creation'],
  },
  {
    id: '0b1c2d',
    created_at: '2024-08-11T16:30:00Z',
    company: {
      id: 'comp963',
      name: 'Artisan Foods',
      description: 'Crafting high-quality, artisanal food products.',
      logo: 'https://picsum.photos/seed/artisanfoods/50/50',
      cover: 'https://picsum.photos/seed/artisanfoods-cover/800/200',
      admin_id: 'admin963',
    },
    title: 'Operations Manager',
    description: 'Oversee daily operations and ensure efficient production processes.',
    work_type: 'Full-time',
    status: 'Open',
    locations: 'Portland, OR',
    industry: 'Food & Beverage',
    tags: ['Operations', 'Management', 'Food Industry'],
  },
  {
    id: '3e4f5g',
    created_at: '2024-08-12T07:50:00Z',
    company: {
      id: 'comp147',
      name: 'Media House',
      description: 'A leading media company providing comprehensive news coverage.',
      logo: 'https://picsum.photos/seed/mediahouse/50/50',
      cover: 'https://picsum.photos/seed/mediahouse-cover/800/200',
      admin_id: 'admin147',
    },
    title: 'Journalist',
    description: 'Investigate and report on news stories across various platforms.',
    work_type: 'Full-time',
    status: 'Open',
    locations: 'Washington, DC',
    industry: 'Media',
    tags: ['Journalism', 'Writing', 'Reporting'],
  },
]
